### ISSUE TITLE
Does this work in termux?

### ISSUE THREAD

**Issue by 0cwa** [pixincreate/PixeneOS#1]
Just curious if your build script might possibly work via a termux environment to install via Custosta afterwards?

Very cool, looking forward to trying this!  (but on a 4a 5g)

**Comment by pixincreate** [comment]
I do think so. I had created an issue at [my-avbroot-setup](https://github.com/chenxiaolong/my-avbroot-setup/issues/2) doubting compatibility issues with Mac and Windows environment.  

Since I hit blocker yesterday citing compatibility issues, I couldn't test this E2E. I'm now planning to go full on CI for this for automated builds and deployments.  

The goal for me here is that, upon every GrapheneOS release, there has to be a build here with all necessary modules installed. A lot of things going in my mind at the moment of me writing this.  

I personally want to use this in the near future.  

That said, I feel this should work on Termux environment **locally** given all the necessary dependencies are installed (I cannot guarantee, yes).

I'll try to update the README today.

**Comment by 0cwa** [comment]
Cool!  Well you got a tester for bramble as soon as I can build a stable image :D  I gotta get a Linux build working before I try a termux one
