### ISSUE TITLE
Error decoding base64

### ISSUE THREAD

**Issue by 0cwa** [pixincreate/PixeneOS#13]
I get this issue with git actions and locally building:

```
Decoding keys from base64...
Error decoding base64 for AVB_BASE64
Error decoding base64 for CERT_OTA_BASE64
Error decoding base64 for OTA_BASE64
Failed to decode keys from base64.\n
Error: Process completed with exit code 1.
```

Git ENV Secrets are set to:
AVB_KEY
CERT_OTA
OTA_KEY

**Comment by pixincreate** [comment]
yes, this is expected.  
i haven't written the documentation yet as this project still is in its early stages. but for now, below info should suffice is what i believe.

when you call `generate_keys` function from `util_functions.sh`(read below for step by step process), it calls `base64_encode` function in `exchange.sh` for encoding the keys to `base64` so that it can be used in `ci` environments. in fact, it does prints out the base64 values in terminal (or where ever the function is called). 
you need to copy the values and add it as `repository secret` in your github fork. once that is done, these keys should automatically be fetched from there and decoded.

to generate keys, you can execute these in your command line:

```sh
cd pixeneos
source src/util_functions.sh && generate_keys
# you'll be asked for passphrases interactively since you've passed an env variable prior to this
# once done, you should now see base64 encoded values being printed.
```

**Comment by 0cwa** [comment]
Ok, cool, that works!

**Comment by pixincreate** [comment]
- Are you on latest main?
- To me, it looks like an issue with keys and not with PixeneOS. I'm saying this because I too faced this issue back when developing decoder. After I generated the keys and updated the base64 encoded keys in github, it worked
Try doing below:
```sh
source src/util_functions.sh && generate_keys
```

Once generated, you should base64 encoded keys, copy that and update it and try again once.

**Comment by 0cwa** [comment]
Could it be an issue where there is no passphrase for the keys and therefore didn't set the passphrase tokens?  I figured if you have access to the tokens, you already also have access to the passphrase, so there's little point in adding a passphrase

**Comment by pixincreate** [comment]
No, passphrase is mandatory to be passed even if it is empty.  

Passphrase is required to:
- patch ota
- generate csig

Also, do note that not having a passphrase for signing will lead to severe security risks.

**Comment by 0cwa** [comment]
> Also, do note that not having a passphrase for signing will lead to severe security risks.

Why is that?

**Comment by pixincreate** [comment]
> > Also, do note that not having a passphrase for signing will lead to severe security risks.
> 
> Why is that?

It solely exist for the sake of encryption. When you decide to not pass the passphrase, you're accepting the risk of having your keys unencrypted which can be easily accessed by anyone who has access to your PC.

Yes, it is solely optional but I wouldn't recommend that.
