### ISSUE TITLE
[Question] Any support for Pixel-exclusive features and/or LSposed+Pixelify?

### ISSUE THREAD

**Issue by e-t-l** [pixincreate/PixeneOS#43]
I am currently using GrapheneOS rooted with AVBroot, and one of my main goals with rooting was to reimplement some PixelOS-exclusive features using a module like Pixelify. I was disappointed to discover that Pixelify, as well as basically every LSposed module I tried to install, resulted in a boot loop.

Have you tried getting any Pixel features (like Call Screening, Hold For Me, pretty much anything involving Android System Intelligence) to work? Have you had any success?

**Comment by pixincreate** [comment]
Hi there! thanks for reaching out!

Official Magisk by Topjohnwu is completely broken on GrapheneOS. Last time I tried Magisk, I had no root access (except in shell, yes) and no Zygisk. That's why I made a [fork](https://github.com/pixincreate/Magisk) that fixes the root and Zygisk on GrapheneOS.

From what I remember, modules like Pixelify requires you to have LSPosed installed(?). This I believe will **not** work because:

- LSPosed does not work in GrapheneOS
- Pixelify requires LSPosed to work
- Pixelify requires certain apps to be system apps with necessary permissions granted to it (GrapheneOS is all about giving apps the least amount of privilege; even for the user) and might result in device getting bricked if tried when bootloader is locked

Magisk devs are hostile towards GrapheneOS and its users. And hence you can expect little to no response from their end for anything related to GrapheneOS.

> Have you tried getting any Pixel features (like Call Screening, Hold For Me, pretty much anything involving Android System Intelligence) to work? Have you had any success?

I did try stuffs back then and none of them worked. Gave up!

___

At the moment of me writing this, I have got no time (at least, until Feb 2025) to work neither on this project nor test the OS on my phone. But hey, it is pretty stable and is known to work!

The project's README will give you a brief idea about what the additionals that this project injects while signing OTA with your own keys.

**Comment by e-t-l** [comment]
Thanks for your answer! By the way, did you ever get [mGMScompat](https://github.com/pixincreate/mGMSCompat) to be functional, or is it archived because it's hopeless? I too believe it would be incredibly useful to sandbox google apps on any ROM with just a magisk module, but it looks like maybe the project was unsuccessful? What's up with that?

**Comment by pixincreate** [comment]
i bought a pixel and never found the need to develop mGMSCompat. So I archived the project before it even started.

and yes, it is highly complicated than thought. it will do more harm than good. it requires zygisk to be functional to modify source code (about 5k+ lines of code needs to be modified) in run time. active maintenance is a must given how grapheneos is changing.

**Comment by e-t-l** [comment]
Understandable, thank you. I also have a Pixel with GrapheneOS, but I miss a lot of the Pixel-exclusive features (which I had asked about when I opened this issue, lol). I was hoping that mGMScompat would allow me to use stock PixelOS with root and still be able to sandbox GMS. Oh well. It's a monumental project and I'm not surprised it proved unfeasible.

**Comment by pixincreate** [comment]
No. mGMSCompat requires user to have an AOSP based OS like LineageOS. It cannot be used on StockOS.
Also, in order to get mGMSCompat working on StockOS, you would have to completely remove GMS from StockOS which **might** remove all the Pixel Specific features
