### ISSUE TITLE
Additional documentation for self management

### ISSUE THREAD

**Issue by radioaddition** [pixincreate/PixeneOS#62]
Hi there! Currently I'm trying to figure it out, but I'm not very experienced with GH actions. Do you think you could add more documentation about setting up one's own server by forking this repo? The reason I ask is because I'd like to manage my own avb/ota keys

**Comment by pixincreate** [comment]
Hi, thanks for reaching out.  

I've a PR open at #52 that addresses this. I've very limited amount time so that will take a bit of time.

>  I'd like to manage my own avb/ota keys

Yes, that's the goal of this project. User should be able to manage their device with their own keys.

> Do you think you could add more documentation about setting up one's own server by forking this repo? 

I initially did not think about this. Now, I guess, I'll add detailed documentation for self management as well.

Will leave this issue open for now until #52 is merged.

**Comment by radioaddition** [comment]
If user management was the initial goal, maybe setting the repo as a template wouldn't be a bad idea?

**Comment by pixincreate** [comment]
i need to learn about template stuffs which might take some..

yeah, will consider this.
